#
###################################
# Site wide configuration
####################################
#
title: Timo Wagner
email: wagnertimo@gmx.de

# Name of your site (displayed in the header)
name: Timo Wagner

# Short bio or description (displayed in the header)
description: Yet Another Data Something Blog.
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Timo Wagner
  avatar: https://avatars2.githubusercontent.com/u/26152358?v=3&u=3ce04d6d58ef6f11be830f4b1c59ce2db97cfec2&s=400
  job: "Yet Another Data Something Blog."
  bio: "I am passionated about Data Science. I like to crawl the web for data and I am also keen on machine learning algorithms."
  email: wagnertimo@gmx.de
  disqus-shortname: https-wagnertimo-github-io
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: wagnertimo
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: timo-wagner-95168213a/
  skype: #username
  xing: Timo_Wagner44
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  stackoverflow: 7810379/timo-wagner?tab=profile
  medium: @timo.wagner
